### PR TITLE
Update README.md to follow study-template

### PR DESCRIPTION
**Pull request by bernardlee**
Update the General Assembly logo and License sections.

### CODE REVIEW

**Comment by BenGitsCode** [comment]
Did you review #19 ? It looks to be addressed to me. I will merge this and suggest that issue be closed. 

A couple things: 

Reference the heck out of [the wiki](https://github.com/ga-wdi-boston/instructors/wiki) when preparing templates. All of what you need to know is there 99% of the time. 

You missed some things from the wiki, namely the naming convention for the commit and the branch itself. This commit should read:

```git
Update from study-template

Refresh for cohort 016
```

and the branch should have been `016/master`

I will rename your branch when I merge. 👍

**Comment by BenGitsCode** [comment]
I take that back on renaming the branch, it makes no sense to rename it when it will be merged to master and waxed anyway. But I did want you to know the naming conventions. 

Go over the whole wiki when you have time, and always as you're going through process.

pay special attention to [naming conventions](https://github.com/ga-wdi-boston/instructors/wiki/RepositoryNamingConventions) to avoid silly naming mistakes and  [profanity](https://github.com/ga-wdi-boston/instructors/wiki/Profanity) is my favorite wiki and something that I think a lot of people don't understand how important it is. It's important.

**Comment by bernardlee** [comment]
My mistake.  I was only following the repository preparation document.  I'll be sure to read the other ones next time.

**Comment by BenGitsCode** [comment]
Always open to any suggestions/contributions to the wiki. It could use some pruning of it's structure.

**Comment by jrhorn424** [comment]
> It could use some pruning of it's structure.

Any reorganization changes would be an awesome PR. But it's a wiki. So if you want to open a branch and ask for comment, you'll need to figure out how to edit a wiki locally and on a branch. Then push it, notify me, I'll do a diff and provide feedback. Thanks @ga-wdi-boston/core

**Pull request merged**
